spring.application.name=ACS_v2
spring.datasource.username=root
spring.datasource.password=Da1Ta2Ba3Se4_
//spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/acs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.freemarker.expose-request-attributes=true
spring.datasource.url=jdbc:mysql://localhost:3306/acs?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false